"use client";

import { useMemo, useState } from "react";
import type {
  Course,
  NearMissSchedule,
  RankPreference,
  ScheduleConstraints,
  ScheduleSolution,
  SolveOutcome,
  SolverFailure,
  StudentProfile,
} from "@/lib/types";
import type { GridBlock } from "@/lib/grid";
import { computeGridBlocks, gridRange, PALETTE } from "@/lib/grid";
import { buildTimetableSvg } from "@/lib/svg";
import { buildIcs } from "@/lib/ics";
import { solutionRuleViolations } from "@/lib/solver";
import { downloadBlob, downloadText, slugify, svgToPngBlob } from "@/lib/download";
import TimetableGrid from "@/components/TimetableGrid";
import { Badge, Btn, Card, SectionTitle, Stat } from "@/components/ui";

/**
 * Step 5 (§3.5/§3.6): ranked conflict-free timetables, weekly grid, contact
 * hours / credits side panel, PNG + ICS export, and the actionable
 * "no solution" path.
 */

interface Props {
  profile: StudentProfile;
  enrolledCourses: Course[];
  rankBy: RankPreference;
  onRankBy: (r: RankPreference) => void;
  solutions: ScheduleSolution[] | null;
  truncated: boolean;
  solutionIdx: number;
  onSolutionIdx: (i: number) => void;
  failure: SolverFailure | null;
  solveOutcome: SolveOutcome | null;
  nearMiss: NearMissSchedule | null;
  constraints: ScheduleConstraints;
  onSaveDraft: (solution: ScheduleSolution, label: string) => void;
  onBack: () => void;
  onReenroll: () => void;
}

const RANK_LABELS: { id: RankPreference; label: string }[] = [
  { id: "fewest-gaps", label: "Fewest gaps" },
  { id: "most-free-days", label: "Most free days" },
  { id: "earliest-finish", label: "Earliest finish" },
  { id: "preferred-faculty", label: "Preferred faculty" },
];

export default function ScheduleStep({
  profile,
  enrolledCourses,
  rankBy,
  onRankBy,
  solutions,
  truncated,
  solutionIdx,
  onSolutionIdx,
  failure,
  solveOutcome,
  nearMiss,
  constraints,
  onSaveDraft,
  onBack,
  onReenroll,
}: Props) {
  const [saved, setSaved] = useState(false);
  const [exporting, setExporting] = useState(false);

  const active: ScheduleSolution | null =
    solutions && solutions.length > 0
      ? solutions[Math.min(solutionIdx, solutions.length - 1)]
      : null;

  const courseByCode = useMemo(
    () => new Map(enrolledCourses.map((c) => [c.courseCode, c])),
    [enrolledCourses]
  );

  const constraintsActive =
    (constraints?.excludedDays?.length ?? 0) > 0 || (constraints?.excludedRanges?.length ?? 0) > 0;

  const blocks: GridBlock[] = useMemo(() => {
    if (!active) return [];
    const names: Record<string, string> = {};
    for (const [code] of Object.entries(active.placements)) {
      names[code] = courseByCode.get(code)?.courseName ?? code;
    }
    return computeGridBlocks(active.placements, names);
  }, [active, courseByCode]);

  const nearMissBlocks: GridBlock[] = useMemo(() => {
    if (!nearMiss) return [];
    const names: Record<string, string> = {};
    for (const [code] of Object.entries(nearMiss.placements)) {
      names[code] = courseByCode.get(code)?.courseName ?? code;
    }
    return computeGridBlocks(nearMiss.placements, names);
  }, [nearMiss, courseByCode]);

  const courseRows = useMemo(() => {
    if (!active) return [];
    return Object.entries(active.placements).map(([code, p]) => {
      const course = courseByCode.get(code);
      const selfPaced = p.sections.every((s) => s.selfPaced) || p.busy.length === 0;
      return {
        code,
        name: course?.courseName ?? code,
        credits: course?.credits ?? 0,
        type: course && "type" in course ? (course as { type?: string }).type : undefined,
        slots: p.sections.map((s) => s.slotCode).join(" + "),
        faculty: [...new Set(p.sections.flatMap((s) => s.faculty))].join(", "),
        hours: p.busy.length,
        selfPaced,
      };
    });
  }, [active, courseByCode]);

  const totalCredits = courseRows.reduce((s, c) => s + c.credits, 0);
  const selfPacedRows = courseRows.filter((c) => c.selfPaced);
  const realRows = courseRows.filter((c) => !c.selfPaced);

  const termShort = useMemo(() => {
    const m = profile.termLabel.match(/year\s*([^–-]*?)\s*-\s*term\s*(\d)/i);
    return m ? `year-${slugify(m[1])}-term-${m[2]}` : slugify(profile.termLabel);
  }, [profile.termLabel]);

  const svgTitle = profile.termLabel || "Weekly Timetable";

  const exportPng = async () => {
    if (!active) return;
    setExporting(true);
    try {
      const m = active.metrics;
      const svg = buildTimetableSvg({
        title: svgTitle,
        subtitle: `${courseRows.length} subjects · ${totalCredits} credits · generated from the MyCamu term slot sheet`,
        blocks,
        startHour: 8,
        endHour: 17,
        footer: [
          `Weekly contact hours: ${m.weeklyContactHours}   |   Free days: ${m.freeDays}   |   Gaps: ${m.totalGaps} h`,
          m.earliestStart && m.latestEnd ? `Earliest ${m.earliestStart} · Latest end ${m.latestEnd}` : "",
          "Generated by College Timetable Generator",
        ].filter(Boolean) as string[],
      });
      const png = await svgToPngBlob(svg, 2);
      downloadBlob(png, `${termShort}-timetable.png`);
    } finally {
      setExporting(false);
    }
  };

  const exportIcs = () => {
    if (!active) return;
    const entries = Object.entries(active.placements).map(([code, placement]) => ({
      placement,
      courseName: courseByCode.get(code)?.courseName ?? code,
    }));
    const ics = buildIcs(entries, profile);
    downloadText(ics, `${termShort}-timetable.ics`, "text/calendar");
  };

  /* ----------------------------- not solved yet ----------------------------- */
  if (!solutions && !failure) {
    return (
      <div className="space-y-5">
        <Card className="p-8 text-center">
          <p className="text-sm text-slate-500">
            No timetable generated yet. Confirm your subject list and section modes, then hit
            “Find conflict-free timetables”.
          </p>
          <div className="mt-4 flex justify-center gap-2">
            <Btn variant="secondary" onClick={onBack}>
              ← Section modes
            </Btn>
            <Btn onClick={onReenroll}>Subject list</Btn>
          </div>
        </Card>
      </div>
    );
  }

  /* ----------------------------- failure UI ----------------------------- */
  if (!solutions || failure) {
    return (
      <div className="space-y-5">
        <div className="rounded-xl border border-red-300 bg-red-50 px-4 py-3">
          <p className="text-sm font-semibold text-red-800">
            Not possible with this selection — no conflict-free timetable exists.
          </p>
          <p className="mt-0.5 text-xs text-red-700">
            Even ignoring your no-class rules, every complete schedule overlaps somewhere. The best
            (fewest-clash) attempt is rendered below so you can see exactly what&apos;s in the way.
          </p>
        </div>
        <Card className="border-red-200 p-5">
          <div className="mb-2 flex items-center gap-2">
            <Badge tone="red">No valid timetable</Badge>
          </div>
          <p className="text-sm text-slate-700">{failure?.message}</p>
          {failure && failure.impossibleCourses.length > 0 && (
            <div className="mt-4">
              <SectionTitle>Courses that cannot be placed at all</SectionTitle>
              <ul className="list-disc space-y-1 pl-5 text-sm text-slate-700">
                {failure.impossibleCourses.map((c) => (
                  <li key={c.courseCode}>
                    <span className="font-mono font-semibold">{c.courseCode}</span> — {c.reason}
                  </li>
                ))}
              </ul>
            </div>
          )}
          {failure && failure.blockingPairs.length > 0 && (
            <div className="mt-4">
              <SectionTitle>Mutually blocking course pairs</SectionTitle>
              <ul className="list-disc space-y-1 pl-5 text-sm text-slate-700">
                {failure.blockingPairs.map((p, i) => (
                  <li key={i}>
                    <span className="font-mono font-semibold">{p.courseA}</span> and{" "}
                    <span className="font-mono font-semibold">{p.courseB}</span> — {p.reason}
                  </li>
                ))}
              </ul>
              <p className="mt-2 text-xs text-slate-500">
                Relax one of these: drop a subject, switch a course to “alternatives”, or pick
                different sections.
              </p>
            </div>
          )}
          {failure && failure.nearMisses.length > 0 && (
            <div className="mt-4">
              <SectionTitle hint="complete schedules with the fewest overlapping hours">
                Closest schedules — each still has a clash
              </SectionTitle>
              <ul className="space-y-2">
                {failure.nearMisses.map((nm, i) => (
                  <li key={i} className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-2 text-sm">
                    <div className="flex flex-wrap items-center gap-2">
                      <Badge tone="amber">{nm.conflictHours} clashing hour{nm.conflictHours === 1 ? "" : "s"}</Badge>
                      <span className="font-mono text-xs text-slate-700">
                        {Object.entries(nm.assignment)
                          .map(([code, id]) => `${code} ${id.split("::")[1] ?? ""}`)
                          .join(" · ")}
                      </span>
                    </div>
                    <ul className="mt-1 list-disc space-y-0.5 pl-5 text-xs text-slate-600">
                      {nm.clashes.map((c, j) => (
                        <li key={j}>
                          <span className="font-mono">{c.courseA} {c.sectionA}</span> ×{" "}
                          <span className="font-mono">{c.courseB} {c.sectionB}</span>: {c.windows.join(", ")}
                        </li>
                      ))}
                    </ul>
                  </li>
                ))}
              </ul>
              <p className="mt-2 text-xs text-slate-500">
                If a clash above involves times that don’t match your real slot sheet, the PDF
                extraction likely merged neighbouring columns into that section (check its weekly
                hours in the parse preview) — re-upload the file; the extractor now rebuilds each
                column separately.
              </p>
            </div>
          )}
          {nearMiss && nearMissBlocks.length > 0 && (
            <div className="mt-6">
              <SectionTitle hint="complete schedule with the fewest possible clashes — not conflict-free">
                Best possible schedule ({nearMiss.conflictHours} clashing hour
                {nearMiss.conflictHours === 1 ? "" : "s"})
              </SectionTitle>
              <TimetableGrid blocks={nearMissBlocks} />
              <div className="mt-2 space-y-1">
                {nearMiss.clashes.map((c, j) => (
                  <p key={j} className="text-xs font-medium text-red-600">
                    ⚠ <span className="font-mono">{c.courseA} {c.sectionA}</span> overlaps{" "}
                    <span className="font-mono">{c.courseB} {c.sectionB}</span> — {c.windows.join(", ")}
                  </p>
                ))}
              </div>
              <p className="mt-2 text-xs text-slate-500">
                To get a real timetable: drop or swap one of the clashing subjects (or switch a
                course to “alternatives” if it has other sections).
              </p>
            </div>
          )}
        </Card>
        <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3">
          <Btn variant="secondary" onClick={onBack}>
            ← Back
          </Btn>
          <Btn onClick={onReenroll}>Change subject selection</Btn>
        </div>
      </div>
    );
  }

  const m = active!.metrics;

  /* ----------------------------- success UI ----------------------------- */
  const bestViol = constraintsActive ? solutionRuleViolations(solutions![0].placements, constraints) : 0;
  const relaxed = solveOutcome === "relaxed";

  return (
    <div className="space-y-5">
      {/* No-class rule outcome banner */}
      {relaxed && (
        <div className="rounded-xl border border-amber-300 bg-amber-50 px-4 py-3">
          <p className="text-sm font-semibold text-amber-900">
            Your no-class rules can’t all be met — here’s the closest match.
          </p>
          <p className="mt-0.5 text-xs text-amber-800">
            Every option below is still 100% conflict-free. Option #1 breaks the fewest rule hours
            ({bestViol}), e.g. a class on an excluded day or inside an excluded window. Loosen the
            rules on the previous step for a fully rule-respecting schedule.
          </p>
        </div>
      )}
      {solveOutcome === "strict" && constraintsActive && (
        <div className="rounded-xl border border-emerald-300 bg-emerald-50 px-4 py-3">
          <p className="text-sm font-semibold text-emerald-800">
            ✓ All {solutions!.length} option{solutions!.length === 1 ? "" : "s"} respect your
            no-class rules.
          </p>
        </div>
      )}

      {/* Solution switcher + ranking */}
      <Card className="p-4">
        <div className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex flex-wrap items-center gap-2">
            <span className="text-xs font-semibold tracking-wide text-slate-500 uppercase">
              {relaxed
                ? `${solutions.length} conflict-free option${solutions.length === 1 ? "" : "s"} — closest to your rules`
                : `${solutions.length} valid timetable${solutions.length === 1 ? "" : "s"} found`}
            </span>
            {solutions.map((s, i) => {
              const v = constraintsActive
                ? solutionRuleViolations(s.placements, constraints)
                : 0;
              return (
                <button
                  key={i}
                  onClick={() => onSolutionIdx(i)}
                  className={`rounded-lg border px-2.5 py-1.5 text-xs font-medium transition-colors ${
                    i === Math.min(solutionIdx, solutions.length - 1)
                      ? "border-blue-600 bg-blue-600 text-slate-800"
                      : "border-slate-200 bg-white text-slate-600 hover:border-slate-300"
                  }`}
                  title={`${s.metrics.totalGaps}h gaps · ${s.metrics.freeDays} free days${
                    v > 0 ? ` · breaks ${v} no-class rule hour(s)` : ""
                  }`}
                >
                  #{i + 1}
                  {i === 0 ? " ★" : ""}
                  <span className="ml-1 opacity-70">{s.metrics.totalGaps}h gaps</span>
                  {v > 0 && <span className="ml-1 font-semibold text-amber-500">⚠{v}</span>}
                </button>
              );
            })}
            {truncated && (
              <span className="text-[11px] text-amber-600">
                search stopped early (budget) — these are the best found so far
              </span>
            )}
          </div>
          <label className="flex items-center gap-2 text-xs text-slate-500">
            Rank by
            <select
              value={rankBy}
              onChange={(e) => onRankBy(e.target.value as RankPreference)}
              className="rounded-lg border border-slate-300 bg-white px-2 py-1.5 text-xs focus:border-blue-400 focus:outline-none"
            >
              {RANK_LABELS.map((r) => (
                <option key={r.id} value={r.id}>
                  {r.label}
                </option>
              ))}
            </select>
          </label>
        </div>
      </Card>

      <div className="grid gap-5 lg:grid-cols-[1fr_320px]">
        {/* Grid */}
        <Card className="p-4">
          <div className="mb-3 flex items-baseline justify-between">
            <h3 className="font-semibold text-slate-800">{svgTitle}</h3>
            <span className="text-xs text-slate-500">
              {blocks.length > 0
                ? `${m.earliestStart ?? "–"} → ${m.latestEnd ?? "–"}`
                : "no fixed-time classes"}
            </span>
          </div>
          <TimetableGrid blocks={blocks} />
          {selfPacedRows.length > 0 && (
            <div className="mt-3 rounded-lg bg-purple-50 px-3 py-2 text-[11px] text-purple-700">
              Self-paced (administrative slot only, no fixed class):{" "}
              {selfPacedRows.map((r) => `${r.code} ${r.slots}`).join(", ")}
            </div>
          )}
          <div className="mt-3 flex flex-wrap gap-1.5">
            {[...new Set(blocks.map((b) => b.courseCode))].map((code) => (
              <span
                key={code}
                className="inline-flex items-center gap-1.5 rounded-md border px-2 py-0.5 text-[11px] font-medium"
                style={{
                  background: PALETTE[blocks.find((b) => b.courseCode === code)!.colorIndex].soft,
                  borderColor: PALETTE[blocks.find((b) => b.courseCode === code)!.colorIndex].border,
                  color: PALETTE[blocks.find((b) => b.courseCode === code)!.colorIndex].text,
                }}
              >
                <span
                  className="h-2 w-2 rounded-full"
                  style={{
                    background: PALETTE[blocks.find((b) => b.courseCode === code)!.colorIndex].border,
                  }}
                />
                {code} {courseByCode.get(code)?.courseName}
              </span>
            ))}
          </div>
        </Card>

        {/* Side panel */}
        <div className="space-y-4">
          <Card className="p-4">
            <SectionTitle>This term at a glance</SectionTitle>
            <div className="grid grid-cols-2 gap-2">
              <Stat label="Contact hrs/wk" value={m.weeklyContactHours} />
              <Stat label="Total credits" value={totalCredits} />
              <Stat label="Free days" value={`${m.freeDays} / 6`} />
              <Stat label="Gap hours" value={`${m.totalGaps} h`} />
            </div>
          </Card>

          <Card className="p-4">
            <SectionTitle hint="100% of weekly hours, zero overlaps">Enrolled courses</SectionTitle>
            <ul className="space-y-2">
              {realRows.map((r) => (
                <li key={r.code} className="rounded-lg border border-slate-100 bg-slate-50 px-2.5 py-1.5">
                  <div className="flex items-baseline justify-between gap-2">
                    <span className="font-mono text-xs font-bold text-slate-700">{r.code}</span>
                    <span className="text-[11px] text-slate-500">{r.credits} cr</span>
                  </div>
                  <div className="truncate text-xs text-slate-600">{r.name}</div>
                  <div className="mt-0.5 text-[10.5px] text-slate-500">
                    {r.slots} · {r.faculty || "faculty TBD"} · {r.hours} h/wk
                  </div>
                </li>
              ))}
              {selfPacedRows.map((r) => (
                <li key={r.code} className="rounded-lg border border-purple-100 bg-purple-50/50 px-2.5 py-1.5">
                  <div className="flex items-baseline justify-between gap-2">
                    <span className="font-mono text-xs font-bold text-purple-700">{r.code}</span>
                    <span className="text-[11px] text-purple-400">{r.credits} cr</span>
                  </div>
                  <div className="truncate text-xs text-purple-600">{r.name} — self-paced</div>
                </li>
              ))}
            </ul>
          </Card>

          <Card className="space-y-2 p-4">
            <SectionTitle>Export & save</SectionTitle>
            <div className="grid grid-cols-2 gap-2">
              <Btn variant="secondary" onClick={exportPng} disabled={exporting}>
                {exporting ? "Rendering…" : "PNG image"}
              </Btn>
              <Btn variant="secondary" onClick={exportIcs}>
                .ics calendar
              </Btn>
            </div>
            <Btn
              variant="success"
              className="w-full"
              disabled={saved}
              onClick={() => {
                onSaveDraft(active!, `${profile.termLabel || "Timetable"} — option #${Math.min(solutionIdx, solutions!.length - 1) + 1}`);
                setSaved(true);
                setTimeout(() => setSaved(false), 2500);
              }}
            >
              {saved ? "✓ Draft saved" : "Save as draft"}
            </Btn>
            <p className="text-[11px] leading-snug text-slate-500">
              The .ics creates weekly recurring events between each section’s start and end dates
              (self-paced placeholder sections are skipped). Drafts let you compare options before
              finalizing.
            </p>
          </Card>
        </div>
      </div>

      <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white px-4 py-3">
        <Btn variant="secondary" onClick={onBack}>
          ← Back to sections
        </Btn>
        <Btn onClick={onReenroll}>Change subjects</Btn>
      </div>
    </div>
  );
}
