export default function Privacy() {
  return <main className="mx-auto max-w-3xl space-y-5 px-6 py-12"><a href="/" className="underline">← Scheduler</a><h1 className="text-3xl font-bold">Privacy & beta terms</h1>
    <p>This independent student project is not affiliated with any college or with MyCamu. Timetables are planning aids, not enrollment confirmations. Check official registration rules, dates and section availability before enrolling.</p>
    <h2 className="text-xl font-bold">What is stored</h2><p>Supabase stores your email, display name, authentication records, year, completed-course history, parsed term data and saved timetable drafts. Password security and email verification are handled by Supabase Auth; this app never stores plaintext passwords or returns them to the browser. Session cookies are necessary for sign-in.</p>
    <p>Profiles and drafts are private to their owner through database access policies. Operators with infrastructure access can administer the database. Shared term datasets, including faculty names in course exports, become visible to signed-in students after moderator approval. Do not submit student IDs, grades, contact details or other private information in datasets.</p>
    <h2 className="text-xl font-bold">Providers & diagnostics</h2><p>Vercel hosts the app, Supabase provides authentication and storage, and Upstash stores short-lived hashed rate-limit identifiers. When configured, Sentry receives redacted technical error events without request bodies, cookies, replay recordings or user profiles. Hosting providers may retain operational/security logs under their own policies. No advertising analytics are enabled. Course replacement suggestions run locally; academic data is not sent to an AI provider.</p>
    <h2 className="text-xl font-bold">Export & deletion</h2><p>Use “Export my data” to download your workspace and drafts, or export a timetable as PNG/ICS. Use “Request account deletion” while signed in; an administrator will process the request within 30 days. If you cannot sign in, use password reset first, or contact the maintainer through the repository linked in the app (do not post your email or academic history publicly). Private data remains until you delete drafts or request account deletion. Shared datasets may remain without uploader attribution; backups and provider security logs expire according to the operator’s configured retention policy.</p>
    <p className="text-sm text-slate-500">Beta notice updated September 26, 2026. Operators must establish a working support channel and publish their backup retention policy before a public launch.</p>
  </main>;
}
